# NUMPY

In [2]:
cd C:\Users\최재혁\Desktop\jupyter


SyntaxError: invalid syntax (<ipython-input-2-38f058278514>, line 1)

In [25]:
import numpy as np

In [26]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
X

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
test_arry=np.array([1,2,3,4],float)
test_arry
type(test_arry[1])
test_arry.dtype
test_arry.shape

(4,)

In [28]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix
matrix.shape

(3, 4)

In [49]:
tensor=np.array([[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
               [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
               [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
               [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

tensor

array([[[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [ ]:
tensor.shape #4개의 Matrix와 3개의 row와 4개의 colums

In [35]:
tensor.ndim # 차원 수: 3차원

3

In [37]:
tensor.size # data의 총 개수

48

### INDEXING

In [40]:
tensor[3,2,3] # 인덱스로 원소 찾기

4

### SLICING

In [50]:
tensor[:,2:,2:]

array([[[5, 8]],

       [[5, 8]],

       [[3, 4]],

       [[3, 4]]])

## ARANGE

In [51]:
np.arange(30) # list의 range 격

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
np.arange(0,5,0.5) # 0 이상 5미만 0.5단위

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [54]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [55]:
np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

# 행렬연산

In [60]:
np.identity(5) * 5 #diag. matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [70]:
print(np.arange(25).reshape(5,5),"\n")
print(np.diag(np.arange(25).reshape(5,5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 0  6 12 18 24]


# RANDOM SAMPLE

In [74]:
np.random.normal(10,0.2,100)

array([10.03918261,  9.6859187 , 10.3262267 , 10.15579484,  9.92373548,
        9.62621091,  9.89225792, 10.08960028, 10.12186278, 10.175274  ,
       10.07771856,  9.86170202, 10.33048594, 10.30272203,  9.86624441,
       10.3001227 ,  9.91163277, 10.02534402, 10.03895324, 10.1339353 ,
        9.98042251, 10.22632595, 10.13156851,  9.9776467 ,  9.84473572,
       10.13825045,  9.89552638, 10.02827608,  9.97498432,  9.99786489,
        9.94845552,  9.90953105, 10.07130541, 10.03765499, 10.06149219,
        9.96656469, 10.20357506,  9.74595814, 10.10002718, 10.23009045,
        9.72560876, 10.04194252,  9.90442314, 10.11870047,  9.94971332,
        9.93716336,  9.6980374 ,  9.94067659, 10.01687025,  9.89612353,
       10.16339844, 10.08288118,  9.78468639,  9.87109167, 10.01690395,
        9.77404351, 10.07653034, 10.04162054, 10.19642016, 10.41706226,
       10.21221902,  9.8492256 , 10.28218813, 10.03754274,  9.89830023,
       10.09972684, 10.0386378 , 10.08148779, 10.29278068,  9.40

# NUMPY에서의 rbind(),cbind()

In [76]:
a=np.array([1,2,3])
b=np.array([4,5,6])

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.vstack((a,b))  # R에서의 cbind

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.hstack((a,b))  # R에서의 rbind

array([1, 2, 3, 4, 5, 6])